///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("45beb29e-6792-4f06-8eb4-5ba678991e50")]
    public partial class MyTestRepository : RepoGenBaseFolder
    {
        static MyTestRepository instance = new MyTestRepository();
        MyTestRepositoryFolders.Form1AppFolder _form1;
        MyTestRepositoryFolders.PrimeServiceWinFormAppFolder _primeservicewinform;

        /// <summary>
        /// Gets the singleton class instance representing the MyTestRepository element repository.
        /// </summary>
        [RepositoryFolder("45beb29e-6792-4f06-8eb4-5ba678991e50")]
        public static MyTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTestRepository() 
            : base("MyTestRepository", "/", null, 0, false, "45beb29e-6792-4f06-8eb4-5ba678991e50", ".\\RepositoryImages\\MyTestRepository45beb29e.rximgres")
        {
            _form1 = new MyTestRepositoryFolders.Form1AppFolder(this);
            _primeservicewinform = new MyTestRepositoryFolders.PrimeServiceWinFormAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("45beb29e-6792-4f06-8eb4-5ba678991e50")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Form1 folder.
        /// </summary>
        [RepositoryFolder("227f0f87-b23a-4c51-a5ae-b07b5efaf5df")]
        public virtual MyTestRepositoryFolders.Form1AppFolder Form1
        {
            get { return _form1; }
        }

        /// <summary>
        /// The PrimeServiceWinForm folder.
        /// </summary>
        [RepositoryFolder("86a9b25d-0c82-4cd7-bc34-bcb65db809ec")]
        public virtual MyTestRepositoryFolders.PrimeServiceWinFormAppFolder PrimeServiceWinForm
        {
            get { return _primeservicewinform; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTestRepositoryFolders
    {
        /// <summary>
        /// The Form1AppFolder folder.
        /// </summary>
        [RepositoryFolder("227f0f87-b23a-4c51-a5ae-b07b5efaf5df")]
        public partial class Form1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _textInfo;
            RepoItemInfo _button1Info;
            RepoItemInfo _label2Info;
            RepoItemInfo _tbchecknumInfo;

            /// <summary>
            /// Creates a new Form1  folder.
            /// </summary>
            public Form1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("Form1", "/form[@controlname='Form1']", parentFolder, 30000, null, true, "227f0f87-b23a-4c51-a5ae-b07b5efaf5df", "")
            {
                _textInfo = new RepoItemInfo(this, "Text", "?/?/text[@accessiblerole='Text']", 30000, null, "f992c952-cd9c-4e90-85be-ea4acde89ec3");
                _button1Info = new RepoItemInfo(this, "Button1", "button[@controlname='button1']", 30000, null, "ab420390-898b-41a6-bc66-439cefd112a1");
                _label2Info = new RepoItemInfo(this, "Label2", "text[@controlname='label2']", 30000, null, "ca30b168-1197-49af-9a81-3064e43a8c6c");
                _tbchecknumInfo = new RepoItemInfo(this, "TbCheckNum", "text[@controlname='tbCheckNum']", 30000, null, "eef2f472-8508-4ff2-b2d0-8e320ab19380");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("227f0f87-b23a-4c51-a5ae-b07b5efaf5df")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("227f0f87-b23a-4c51-a5ae-b07b5efaf5df")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("f992c952-cd9c-4e90-85be-ea4acde89ec3")]
            public virtual Ranorex.Text Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("f992c952-cd9c-4e90-85be-ea4acde89ec3")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The Button1 item.
            /// </summary>
            [RepositoryItem("ab420390-898b-41a6-bc66-439cefd112a1")]
            public virtual Ranorex.Button Button1
            {
                get
                {
                    return _button1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button1 item info.
            /// </summary>
            [RepositoryItemInfo("ab420390-898b-41a6-bc66-439cefd112a1")]
            public virtual RepoItemInfo Button1Info
            {
                get
                {
                    return _button1Info;
                }
            }

            /// <summary>
            /// The Label2 item.
            /// </summary>
            [RepositoryItem("ca30b168-1197-49af-9a81-3064e43a8c6c")]
            public virtual Ranorex.Text Label2
            {
                get
                {
                    return _label2Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Label2 item info.
            /// </summary>
            [RepositoryItemInfo("ca30b168-1197-49af-9a81-3064e43a8c6c")]
            public virtual RepoItemInfo Label2Info
            {
                get
                {
                    return _label2Info;
                }
            }

            /// <summary>
            /// The TbCheckNum item.
            /// </summary>
            [RepositoryItem("eef2f472-8508-4ff2-b2d0-8e320ab19380")]
            public virtual Ranorex.Text TbCheckNum
            {
                get
                {
                    return _tbchecknumInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TbCheckNum item info.
            /// </summary>
            [RepositoryItemInfo("eef2f472-8508-4ff2-b2d0-8e320ab19380")]
            public virtual RepoItemInfo TbCheckNumInfo
            {
                get
                {
                    return _tbchecknumInfo;
                }
            }
        }

        /// <summary>
        /// The PrimeServiceWinFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("86a9b25d-0c82-4cd7-bc34-bcb65db809ec")]
        public partial class PrimeServiceWinFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _text65535Info;

            /// <summary>
            /// Creates a new PrimeServiceWinForm  folder.
            /// </summary>
            public PrimeServiceWinFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PrimeServiceWinForm", "/form[@title='']", parentFolder, 30000, null, true, "86a9b25d-0c82-4cd7-bc34-bcb65db809ec", "")
            {
                _text65535Info = new RepoItemInfo(this, "Text65535", "text[@controlid='65535']", 30000, null, "1579f453-5ef0-4279-83aa-99c8b1ea8264");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("86a9b25d-0c82-4cd7-bc34-bcb65db809ec")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("86a9b25d-0c82-4cd7-bc34-bcb65db809ec")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text65535 item.
            /// </summary>
            [RepositoryItem("1579f453-5ef0-4279-83aa-99c8b1ea8264")]
            public virtual Ranorex.Text Text65535
            {
                get
                {
                    return _text65535Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text65535 item info.
            /// </summary>
            [RepositoryItemInfo("1579f453-5ef0-4279-83aa-99c8b1ea8264")]
            public virtual RepoItemInfo Text65535Info
            {
                get
                {
                    return _text65535Info;
                }
            }
        }

    }
#pragma warning restore 0436
}
