///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording2 recording.
    /// </summary>
    [TestModule("106ecc47-bc27-4727-bf05-3e4ff32d4d5c", ModuleType.Recording, 1)]
    public partial class Recording2 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTestRepository repository.
        /// </summary>
        public static MyTestRepository repo = MyTestRepository.Instance;

        static Recording2 instance = new Recording2();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording2()
        {
            FalseValue = "";
            FalseResult = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording2 Instance
        {
            get { return instance; }
        }

#region Variables

        string _FalseValue;

        /// <summary>
        /// Gets or sets the value of variable FalseValue.
        /// </summary>
        [TestVariable("3ad90d89-207a-4b3f-93ba-4ca3de03572b")]
        public string FalseValue
        {
            get { return _FalseValue; }
            set { _FalseValue = value; }
        }

        string _FalseResult;

        /// <summary>
        /// Gets or sets the value of variable FalseResult.
        /// </summary>
        [TestVariable("d36ef218-5c6f-49db-8dea-328c1d7c95ee")]
        public string FalseResult
        {
            get { return _FalseResult; }
            set { _FalseResult = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Form1.Text' at 166;15.", repo.Form1.TextInfo, new RecordItemIndex(0));
            repo.Form1.Text.Click("166;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'а' with focus on 'Form1.Text'.", repo.Form1.TextInfo, new RecordItemIndex(1));
            repo.Form1.Text.PressKeys("а");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Некорретно введены данные. Пожалуйста, введите положительное целое число.') on item 'PrimeServiceWinForm.Text65535'.", repo.PrimeServiceWinForm.Text65535Info, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.PrimeServiceWinForm.Text65535Info, "Text", "Некорретно введены данные. Пожалуйста, введите положительное целое число.");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PrimeServiceWinForm' at 200;37.", repo.PrimeServiceWinForm.SelfInfo, new RecordItemIndex(3));
            repo.PrimeServiceWinForm.Self.Click("200;37");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
